Tatyana E.: Updates for API testing project
tatyana-evtikhova/automated_testing_projects pull request #1
Opened 2024-03-30 15:38 UTC by tatyana-evtikhova

2024-03-31 16:02 UTC, eugene-okulik requested changes
Теперь всё выглядит намного лучше. Одно но - создание мема из от имени другого пользователя - это не отдельный эндпоинт. Ведь ты при этом не идешь на другой url, например. У тебя просто меняется одно поле в отправке запроса.  
Ведь класс для создания нового мема у тебя выглядит так:
```python
class CreateMeme(Endpoint):
    meme_id = None

    @allure.step('Create a new meme')
    def new_meme(self, payload):
        response = self.session.post(f"{self.url}/meme", json=payload)
        return response
```
То есть ты просто помещаешь новый метод сюда же в этот класс:
```python
class CreateMeme(Endpoint):
    meme_id = None

    @allure.step('Create a new meme')
    def new_meme(self, payload):
        response = self.session.post(f"{self.url}/meme", json=payload)
        return response

    @allure.step('Create a new meme by user mascot')
    def create_meme_as_mascot(self, payload):
        headers = {'Authorization': f'{self.get_token_mascot()}'}
        response = self.session.post(f"{self.url}/meme", json=payload, headers=headers)
        return response
```
То же самое и с delete и с put и с get. Для этого всего не нужны отдельные классы. Мы и создаем по классу на каждый эндпоинт, чтобы внутри этого класса было все, что нам может понадобиться при работе с этим эндпоинтом.

2024-03-31 16:02 UTC, eugene-okulik commented on .gitignore
> +locustfile.py
locustfile.py является файлом с кодом. Его очень желательно хранить в репозиории.

2024-04-01 09:37 UTC, tatyana-evtikhova commented on .gitignore
> +locustfile.py
Привет, сделала соответствующие изменения в новом коммите. Спасибо за обратную связь - код стал в разы приятнее :)

2024-04-02 06:38 UTC, eugene-okulik approved these changes
Вот теперь клево. Файл с тестами разрастается и можно разделить его не несколько. Не обязательно по файлу на эндпоинт. Можно, например, все негативные вынести в один, позитивные в другой.  
Заканчиваем с этим. Можешь мержить и идем дальше.

2024-04-02 07:41 UTC, merged